---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.name }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.servicePort }}
    targetPort: {{ .Values.servicePort }}
    nodePort: {{ .Values.nodePort }}