---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxUnavailable: "30%"
      maxSurge: "30%"
  selector:
    matchLabels:
      app: {{ .Values.name }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        active: "yes"
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.name }}:{{ .Values.image.rev }}
        imagePullPolicy: Never
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        env:
        - name: FORCE_RESTART
          value: "{{ now.Unix }}"
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.servicePort }}
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.servicePort }}