---
# Source: app2/templates/02_services.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: app2
  namespace: app2
  labels:
    app: app2
spec:
  type: NodePort
  selector:
    app: app2
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 32001