---
# Source: app1/templates/03_deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: app1
  labels:
    app: app1
spec:
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxUnavailable: "30%"
      maxSurge: "30%"
  selector:
    matchLabels:
      app: app1
  replicas: 1
  template:
    metadata:
      labels:
        app: app1
        active: "yes"
    spec:
      containers:
      - name: app1
        image: app1:local
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 1
            memory: 64Mi
        env:
        - name: FORCE_RESTART
          value: "1575140984"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080